name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write         # Required for OIDC
  contents: read

env:
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ dev, prod ]

    defaults:
      run:
        working-directory: ./envs/${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        # Note: no client-secret needed for OIDC

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan-${{ matrix.environment }}

      - name: Upload tfplan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-${{ matrix.environment }}
          path: tfplan-${{ matrix.environment }}

  apply:
    name: Terraform Apply (Manual Approval)
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        environment: [ dev, prod ]

    defaults:
      run:
        working-directory: ./envs/${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3

      - name: Download tfplan
        uses: actions/download-artifact@v3
        with:
          name: tfplan-${{ matrix.environment }}
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan-${{ matrix.environment }}
