name: Terraform CI/CD for AKS

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true

jobs:
  validate-plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=environments/${{ matrix.environment }} init

      - name: Terraform Validate
        run: terraform -chdir=environments/${{ matrix.environment }} validate

      - name: Terraform Plan
        run: terraform -chdir=environments/${{ matrix.environment }} plan -out=tfplan-${{ matrix.environment }}.out

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}/tfplan-${{ matrix.environment }}.out

  apply:
    name: Terraform Apply with Manual Approval
    needs: validate-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        environment: [dev, prod]

    environment:
      name: ${{ matrix.environment }}
      url: https://portal.azure.com/

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=environments/${{ matrix.environment }} init

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}

      - name: Terraform Apply
        run: terraform -chdir=environments/${{ matrix.environment }} apply tfplan-${{ matrix.environment }}.out
